### ISSUE TITLE
dont depend on global truffle install

### ISSUE THREAD

**Issue by axelhodler** [OpenMined/Sonar#11]
currently we use `npm install -g truffle`. Meaning the truffle version (and thus the solidity compiler) will be different on every developers system. IMHO this always leads to issues.

suggestion:
init `package.json`, install `truffle` there and call via `./node_modules/.bin/truffle`, this can be abstracted into a `truffle.sh`. what do you think?

@anoff

**Comment by anoff** [comment]
Sounds great! However we shouldn't introduce `.sh` files as entry points.
Instead try to abstract calls with `npm run truffle/migrate..` or a `Makefile`.  That way we can have a single (_or double_ 🙄) entrypoint for scripts across all repositories in OpenMined.
The `make/npm` could call a `.sh` behind the scenes though of course.

**Comment by axelhodler** [comment]
good idea, forgot the `npm scripts` functionality there for a moment

**Comment by axelhodler** [comment]
in progress
