### ISSUE TITLE
static addresses in docker image

### ISSUE THREAD

**Issue by anoff** [OpenMined/Sonar#5]
To improve ease of development and lower the entry barrier it would be awesome if we could publish a sonar docker image that has a static contract address.

**Acceptance Criteria**
* automated deployment
* same address for every pull
* optional: same address for every new image version

**Comment by anoff** [comment]
> Milestone: hydrogen

**Comment by anoff** [comment]
Did some (a lot) of research now and I'm 90% sure there is no way to deploy a contract to a pre-defined address. However @TheOriginalAlex and me figured out how to (manually) bake a docker image that includes the contract already. Now all that's left is automate it.

**Comment by samsontmr** [comment]
Haven't had time to try this out, but @anoff and I were thinking a shell script might be able to do this (in case anyone wants to try it out ;).

**Comment by anoff** [comment]
Currently working on it on a fork. The bash script should be working..

**Comment by iamtrask** [comment]
@anoff this research is probably blogpost-worthy. I'm going to open a new file in the Docs repo for us to aggregate ideas for blogpost contributions.

**Comment by anoff** [comment]
@iamtrask just ping me if you need an editor somewhere or if I should guest author/ghostwrite 👻📝

Closing this issue because I forgot the properly link the PR that should have done this automagically.

**Comment by iamtrask** [comment]
You should definitely write it (and not ghostwrite!). I'll definitely read it and help guide, but you're the expert man!
